cc_binary(
    name = 'orc-contents',
    srcs = 'FileContents.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)

cc_binary(
    name = 'orc-scan',
    srcs = 'FileScan.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)


cc_binary(
    name = 'orc-metadata',
    srcs = 'FileMetadata.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)


cc_binary(
    name = 'orc-statistics',
    srcs = 'FileStatistics.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)


cc_binary(
    name = 'orc-memory',
    srcs = 'FileMemory.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)


cc_binary(
    name = 'timezone-dump',
    srcs = 'TimezoneDump.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)


cc_binary(
    name = 'csv-import',
    srcs = 'CSVFileImport.cc',
    deps = [
        '//:ocr',
        '//thirdparty/snappy:snappy',
        '#lz4'
    ],
    incs = ['../../include', '../../src']
)

